/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */



pluginManagement {
 repositories {
  google()
  gradlePluginPortal()
  mavenCentral()
 }
}

dependencyResolutionManagement {
 repositories {
  google()
  mavenCentral()
 }
}

plugins {
 // Apply the foojay-resolver plugin to allow automatic download of JDKs
 id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "event-threads"
include("lib")
